# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a774b8d10dc790c503b64e4a5ad635b3b2ccb7ca2a0a9f8740370d9583a5e152beee4b727e39ebad6e277bbf1c936a320225a00893e371919377c37cdcc29bcb

test:
  secret_key_base: 8452e56e719c8ea2a1c1e3e4af04f15777444fe50a01d25d3fbe10029ee264eab6488cbc79060fbe850777c82b26ee90cd9fa74e10ecf020ac62f38a4bca8a18

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
